### ISSUE TITLE
AlreadyDisposedException Cannot create light service com.intellij.ide.navbar.ide.NavBarService because container is already disposed 

### ISSUE THREAD

**Issue by abn-dev-01** [michaelestermann/WindowLayoutManager#37] opened 2023-06-28 11:22 UTC
Hi again. 
I got the AlreadyDisposedException

IntelliJ IDEA 2023.1.3 (Ultimate Edition)
Build #IU-231.9161.38, built on June 20, 2023

com.intellij.serviceContainer.AlreadyDisposedException: Cannot create light service com.intellij.ide.navbar.ide.NavBarService because container is already disposed (container=Project(name=telekom, containerState=DISPOSE_COMPLETED, componentStore=C:\P\telekom) (disposed))
      at com.intellij.serviceContainer.ContainerUtilKt.throwAlreadyDisposedError(containerUtil.kt:40)
      at com.intellij.serviceContainer.ComponentManagerImpl.checkThatCreatingOfLightServiceIsAllowed(ComponentManagerImpl.kt:790)
      at com.intellij.serviceContainer.ComponentManagerImpl.getOrCreateLightService(ComponentManagerImpl.kt:770)
      at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:726)
      at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:670)
      at com.intellij.ide.navbar.ide.NavBarService$Companion.getInstance(NavBarService.kt:165)
      at com.intellij.ide.navbar.ide.NavBarService.getInstance(NavBarService.kt)
      at com.intellij.ide.navigationToolbar.MyNavBarWrapperPanel.uiSettingsChanged(NavBarRootPaneExtension.java:149)
      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.base/java.lang.reflect.Method.invoke(Method.java:568)
      at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:120)
      at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:85)
      at jdk.proxy2/jdk.proxy2.$Proxy35.uiSettingsChanged(Unknown Source)
      at com.intellij.ide.ui.UISettings.fireUISettingsChanged(UISettings.kt:672)
      at com.layoutmanager.layout.restore.RestoreLayoutAction.applyEditorTabPlacement(RestoreLayoutAction.java:71)
      at com.layoutmanager.layout.restore.RestoreLayoutAction.applyLayout(RestoreLayoutAction.java:51)
      at com.layoutmanager.layout.restore.RestoreLayoutAction.actionPerformed(RestoreLayoutAction.java:46)
      at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:333)
      at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:307)
      at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:356)
      at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:307)
      at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$performAction$5(ActionMenuItem.java:299)
      at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:225)
      at com.intellij.openapi.actionSystem.impl.ActionMenuItem.performAction(ActionMenuItem.java:292)
      at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$new$0(ActionMenuItem.java:67)
      at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
      at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$4(ActionMenuItem.java:114)
      at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
      at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
      at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:114)
      at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:526)
      at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:558)
      at java.desktop/java.awt.Component.processMouseEvent(Component.java:6656)
      at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
      at java.desktop/java.awt.Component.processEvent(Component.java:6421)
      at java.desktop/java.awt.Container.processEvent(Container.java:2266)
      at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
      at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
      at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
      at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
      at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
      at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
      at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
      at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2804)
      at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
      at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:790)
      at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
      at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
      at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
      at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
      at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
      at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:763)
      at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:761)
      at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
      at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
      at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:760)
      at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:667)
      at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:615)
      at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:570)
      at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
      at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
      at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
      at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
      at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
      at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
      at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
      at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
      at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
      at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
      at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
      at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
      at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
      at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
      at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
      at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
      at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
      at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by michaelestermann** [comment] 2024-02-23 09:55
Duplicate of #36

**Closed by michaelestermann** 2024-02-23 09:55 UTC
